### ISSUE TITLE
Default value is not recorded for useFirstResult / useSingleResult 

### ISSUE THREAD

**Issue by MarcelRobitaille** [augustocdias/vscode-shell-command#117]
The default value is not recorded for useFirstResult / useSingleResult . 

It's only recorded in the else branch.
https://github.com/augustocdias/vscode-shell-command/blob/master/src/lib/CommandHandler.ts#L172

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

This change addresses the issue where the default value is not recorded for useFirstResult and useSingleResult cases. We modify the handle() method in the CommandHandler class to record the input value before returning it in these cases.

I also created pull request: https://github.com/augustocdias/vscode-shell-command/pull/118


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
